Feat/#69 request details page
Flutterando/calamidade pull request #129
Opened 2024-05-16 20:33 UTC by NilsonSoares

Criada a página de detalhes da requisição.

![request_details_page](https://github.com/Flutterando/calamidade/assets/19718447/4cfd6851-57d0-4cb0-a5df-e642e9d3ec06)

2024-05-16 20:42 UTC, dtodt submitted a review, later dismissed

2024-05-16 20:56 UTC, LeBaleiro requested changes

2024-05-16 20:56 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class RequestHeader extends StatelessWidget {
sugiro mover esse widget para outro arquivo para não deixar esse arquivo muito grande e para ficar mais fácil de localizar as coisas no projeto

2024-05-16 20:56 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class UserDetails extends StatelessWidget {
mesmo comentário

2024-05-16 20:56 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class CreatedAtDate extends StatelessWidget {
mesmo comentário

2024-05-16 20:56 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class StatusDetails extends StatelessWidget {
mesmo comentário

2024-05-16 20:56 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class StatusTag extends StatelessWidget {
mesmo comentário

2024-05-16 20:57 UTC, tabatasaantos approved these changes

2024-05-16 20:59 UTC, LeBaleiro requested changes

2024-05-16 20:59 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +          'João Maria da silva',
```suggestion
          user.name,
```

2024-05-16 20:59 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +              'Estância Velha', //TODO: adicionar o endereço
```suggestion
              user.city, //TODO: adicionar o endereço
```

2024-05-16 20:59 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +              '+55 (51) 9 1234-5648', //TODO: adicionar telefone
```suggestion
              user.phoneNumber, //TODO: adicionar telefone
```

2024-05-16 21:00 UTC, tganzerli requested changes

2024-05-16 21:00 UTC, tganzerli commented on core_module/lib/core_module.dart
> +export 'src/helpers/validators_helper.dart';
O export esta duplicado.

2024-05-16 21:04 UTC, LeBaleiro requested changes

2024-05-16 21:04 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +              'Estância Velha', //TODO: adicionar o endereço
não tenho certeza se o city vem do user, mas caso não venha, seria bom passar city por parametro já para o widget, aí a gente não precisa lembrar de voltar nesse widget depois

2024-05-16 21:04 UTC, LeBaleiro commented on app/lib/app/(public)/request_details/request_details_card.dart
> +              '+55 (51) 9 1234-5648', //TODO: adicionar telefone
mesma coisa aqui, o phoneNumber vir do user ou por parametro

2024-05-16 21:15 UTC, dtodt commented
Verificar comentários.

2024-05-16 22:00 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class RequestHeader extends StatelessWidget {
> sugiro mover esse widget para outro arquivo para não deixar esse arquivo muito grande e para ficar mais fácil de localizar as coisas no projeto

movido para a pasta de widgets e renomeado para um nome mais descritivo.

2024-05-16 22:01 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class UserDetails extends StatelessWidget {
movido para a pasta de widgets e renomeado para um nome mais descritivo.

2024-05-16 22:01 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class CreatedAtDate extends StatelessWidget {
movido para a pasta de widgets e renomeado para um nome mais descritivo.

2024-05-16 22:01 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class StatusDetails extends StatelessWidget {
movido para a pasta de widgets e renomeado para um nome mais descritivo.

2024-05-16 22:01 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +class StatusTag extends StatelessWidget {
movido para a pasta de widgets e renomeado para um nome mais descritivo.

2024-05-16 22:02 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +          'João Maria da silva',
alterado

2024-05-16 22:02 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +              'Estância Velha', //TODO: adicionar o endereço
alterado,

2024-05-16 22:03 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/request_details_card.dart
> +              '+55 (51) 9 1234-5648', //TODO: adicionar telefone
alterado.

2024-05-16 22:03 UTC, NilsonSoares commented on core_module/lib/core_module.dart
> +export 'src/helpers/validators_helper.dart';
removida o export duplicado.

2024-05-16 22:24 UTC, wellgenio approved these changes

2024-05-16 22:37 UTC, DiegoSCastro commented on app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_user_details.dart
> +        ),
provavelmente vai precisar um dos elementos de cada row dentro de 1 expanded ou flexible para evitar overflow.
Faça o teste com uma string grande

2024-05-16 23:13 UTC, NilsonSoares commented on app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_user_details.dart
> +        ),
feito.

2024-05-16 23:16 UTC, DiegoSCastro approved these changes

2024-05-17 00:30 UTC, pedroserretti requested changes
Opa mano, tranquilo? :)

A tela está diferente um pouco do figma.
Por exemplo a tag da situação alta, ícone e dados escritos tipo "cidade" e "telefone"
Tenta fazer o máximo parecido com o design do figma!

https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=iOy7vCOx3RYIJ0X3-0

![331387072-32407412-8bc6-4d5e-991c-a22fc50f0f1b](https://github.com/Flutterando/calamidade/assets/109255580/cac8d307-3c74-4cd4-b686-04eb185c4770)

2024-05-17 01:38 UTC, jacobaraujo7 approved these changes
LGTM

2024-05-17 01:38 UTC, merged