feat: Criando contrato de cache
Flutterando/calamidade pull request #33
Opened 2024-05-14 20:02 UTC by tganzerli

2024-05-14 20:56 UTC, viniciusddrft approved these changes

2024-05-14 23:22 UTC, dtodt commented on core_module/lib/core_module.dart
> +export 'src/cache/cache.dart';
Este export poderia ficar antes do entities para ficar em ordem alfabética.

2024-05-15 00:32 UTC, Matheysmota approved these changes

2024-05-15 01:00 UTC, kiszewski approved these changes

2024-05-15 01:42 UTC, dtodt requested changes
Ver comentário

2024-05-15 11:39 UTC, tganzerli commented on core_module/lib/core_module.dart
> +export 'src/cache/cache.dart';
Feito

2024-05-15 12:42 UTC, tganzerli commented
> Será feito a implementação também nesse pr ?

posso, fazer.

2024-05-15 13:17 UTC, jacobaraujo7 approved these changes

2024-05-15 13:17 UTC, dtodt approved these changes

2024-05-15 13:19 UTC, merged