feat: add theme of text field
Flutterando/calamidade pull request #39
Opened 2024-05-14 22:45 UTC by CarlosYanBezerraVieira

#37

2024-05-14 23:16 UTC, dtodt commented
👀

2024-05-14 23:18 UTC, dtodt commented on design_system/lib/src/themes/theme.dart
> +class CoopartilharColorsExtension
@jacobaraujo7

2024-05-15 01:40 UTC, dtodt requested changes
Verificar comentário.

2024-05-15 12:32 UTC, jacobaraujo7 commented
Verifique os conflitos.
Cuidado com os nomes dos commits

2024-05-15 12:32 UTC, closed without merging

2024-05-15 12:33 UTC, CarlosYanBezerraVieira commented
Vou subir um novo pull essa branch ta meio bugada aqui na minha maquina