Feat/#66 core: Criar implementação do http client
Flutterando/calamidade pull request #90
Opened 2024-05-15 18:06 UTC by felipezfr

2024-05-15 19:48 UTC, tganzerli commented on core_module/lib/src/client/dio/rest_client_dio_impl.dart
> +      connectTimeout: const Duration(seconds: 5),
Vai manter o tempo em 5 segundos ou não esta parte não foi refletida?

2024-05-15 19:57 UTC, felipezfr commented on core_module/lib/src/client/dio/rest_client_dio_impl.dart
> +      connectTimeout: const Duration(seconds: 5),
Podemos conversar com o pessoal do backend para ver qual valor fica melhor

2024-05-16 01:13 UTC, DiegoSCastro approved these changes

2024-05-16 09:57 UTC, dtodt requested changes
Ver comentário.

2024-05-16 09:57 UTC, dtodt commented on core_module/lib/src/client/i_rest_client.dart
> +  Future<RestClientResponse> post(RestClientRequest request);
A remoção da inferencia de tipo ocasionou breaking changes no projeto, favor atualizar os repositories que já estão usando o contrato, removendo o tipo.

```sh
  error • The method 'Future<RestClientResponse> Function(RestClientRequest)' is declared with 0 type parameters, but 1 type arguments are given • lib/app/features/request_details/data/request_details_repository_impl.dart:17:15 • wrong_number_of_type_arguments_method
```

2024-05-16 12:27 UTC, LuisRibeiroo commented on core_module/lib/src/client/dio/client_interceptor_dio_impl.dart
> +    }
Para esse caso não seria bom termos um else genérico chamando o super? Pq caso o erro seja algo que não tenha sido tratado de alguma forma, pelo menos o processo não para sem dar um retorno pras camadas superiores.

Em tempo, talvez seja legal usar um `switch` com esse retorno, que ficaria bem simples de ler.
```
return switch(message){
    RestClientException => ... ,
    RestClientResponse => ... ,
    _ => super.onError(err),
};
```

2024-05-16 12:27 UTC, LuisRibeiroo commented on core_module/lib/src/client/dio/client_interceptor_dio_impl.dart
> +    }
A mesma coisa do comentário do onError.

2024-05-16 12:27 UTC, LuisRibeiroo commented on core_module/lib/src/client/dio/client_interceptor_dio_impl.dart
> +    }
A mesma coisa do comentário do onError.

2024-05-16 12:27 UTC, LuisRibeiroo commented on core_module/lib/src/client/dio/dio_adapter.dart
> +class DioAdapter {
Todos os métodos dessa classe realmente devem ser visíveis externamente? Caso não, seria uma boa mudarmos pra privado pra evitar o uso errado em algum outro local.

2024-05-16 12:27 UTC, LuisRibeiroo commented on core_module/lib/src/client/dio/rest_client_dio_impl.dart
> +      connectTimeout: const Duration(seconds: 5),
Pra deixar esse cara mais simples, não poderíamos jogar essa info pra uma variável de ambiente? Assim o código fica pronto e o que muda é apenas o valor configurado no momento do build.

2024-05-16 12:27 UTC, LuisRibeiroo commented on core_module/lib/src/client/rest_client_exception.dart
> +class RestClientException implements Exception, RestClientHttpMessage {
Essa implementação poderia ser sobre o `BaseException`, não poderia?

2024-05-16 14:02 UTC, felipezfr commented on core_module/lib/src/client/i_rest_client.dart
> +  Future<RestClientResponse> post(RestClientRequest request);
Foi removido para viabilizar o uso dos interceptors.

2024-05-16 14:03 UTC, felipezfr commented on core_module/lib/src/client/dio/client_interceptor_dio_impl.dart
> +    }
Por questão de tempo, por enquanto deixaremos assim.

2024-05-16 14:04 UTC, felipezfr commented on core_module/lib/src/client/dio/client_interceptor_dio_impl.dart
> +    }
Por questão de tempo, por enquanto deixaremos assim.

2024-05-16 14:09 UTC, felipezfr commented on core_module/lib/src/client/rest_client_exception.dart
> +class RestClientException implements Exception, RestClientHttpMessage {
Feito

2024-05-16 14:14 UTC, merged